name: Release Tauri App

on:
  push:
    tags:
      - 'v*'

jobs:
  tauri-build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Build Tauri app
        run: npm run tauri build

      - name: Rename artifacts
        shell: bash
        run: |
          cd src-tauri/target/release/bundle

          if [[ "${{ matrix.platform }}" == "macos-latest" ]]; then
            mv dmg/*.dmg myapp-mac.dmg || true
          elif [[ "${{ matrix.platform }}" == "windows-latest" ]]; then
            mv msi/*.msi myapp-windows.msi || true
          elif [[ "${{ matrix.platform }}" == "ubuntu-latest" ]]; then
            mv appimage/*.AppImage myapp-linux.AppImage || true
            mv deb/*.deb myapp-linux.deb || true
          fi

      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            src-tauri/target/release/bundle/*.dmg
            src-tauri/target/release/bundle/*.msi
            src-tauri/target/release/bundle/*.AppImage
            src-tauri/target/release/bundle/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
